### ISSUE TITLE
TypeScript: Errors on react-konva refs

### ISSUE THREAD

**Issue by andytan0727** [konvajs/react-konva#316]
When I try to simulate the hover animation example from [Expand Images on Hover](https://konvajs.github.io/docs/sandbox/Expand_Images_on_Hover.html)
 on my project with **TypeScript** with regards to **React refs**, I have stumbled several errors. Below is the code example that I have the errors:

```typescript
import { Circle, Layer, Group, Text } from "react-konva";

interface AProps {
  ...
}

export default class A extends React.Component<AProps, {}> {
  private layer: React.RefObject<typeof Layer>;

  constructor(props: AProps) {
    super(props);
    this.layer = React.createRef<typeof Layer>();
  }

  handleExpand = e => {
    const shape = e.target;
    document.body.style.cursor = "pointer";
    shape.scaleX(1.5);
    shape.scaleY(1.5);
    this.layer.current!.draw();
  };

  handleRestore = e => {
    const shape = e.target;
    document.body.style.cursor = "default";
    shape.scaleX(1);
    shape.scaleY(1);
    this.layer.current!.draw();
  };

  render() {
    const { width, color } = this.props;
    return (
      <Layer ref={this.layer}>
        <Circle
          x={x}
          y={y}
          radius={width / 2 - 10}
          fill={color}
          stroke={'#000000'}
          strokeWidth={2}
        />
      </Layer>
    );
  }
}
```

The errors are as following:
- `this.layer.current!.draw();` - Property 'draw' does not exist on type 'KonvaContainerComponent<Layer<Node>, LayerConfig>'.
- `ref={this.layer}` - Type 'RefObject<KonvaContainerComponent<Layer<Node>, LayerConfig>>' is not assignable to type 'string | ((instance: Layer<Node> | null) => void) | RefObject<Layer<Node>> | null | undefined'.
  Type 'RefObject<KonvaContainerComponent<Layer<Node>, LayerConfig>>' is not assignable to type 'RefObject<Layer<Node>>'.
    Type 'KonvaContainerComponent<Layer<Node>, LayerConfig>' is missing the following properties from type 'Layer<Node>': getIntersection, enableHitGraph, disableHitGraph, clearBeforeDraw, and 128 more.

**Comment by lavrton** [comment]
It will be really good if you can debug that issue, and fix our typescript definitions.

I will take a look into the issue later. Any Pull Requests are welcome.

**Comment by zivni** [comment]
You should import the Layer for the ref from Konva not from react-konva. that is
```TS
import * as Konva from "konva"
import { Circle, Layer, Group, Text } from "react-konva";
//and then
private layer: React.RefObject<typeof Konva.Layer>;
```

**Comment by andytan0727** [comment]
@zivni ya I think I tested that before. TypeScript still making noises with that change:

> Type 'RefObject<typeof Layer>' is not assignable to type 'string | ((instance: Layer<Node> | null) => void) | RefObject<Layer<Node>> | null | undefined'.
  Type 'RefObject<typeof Layer>' is not assignable to type 'RefObject<Layer<Node>>'.
    Type 'typeof Layer' is missing the following properties from type 'Layer<Node>': getIntersection, enableHitGraph, disableHitGraph, clearBeforeDraw, and 128 more.

I couldn't figure out a way to solve this at present time. For the sake of time I have taken another approach to animation by using react-spring as specified in react-konva doc.

**Comment by lavrton** [comment]
Just tried with the last version of `konva@3.2.0` and `react-konva@16.8.5.-0`. Looks like it works ok now:

```javascript
class App extends Component {
  private layer: React.RefObject<Konva.Layer> = React.createRef();
  render() {
    return (
      <Stage width={window.innerWidth} height={window.innerHeight}>
        <Layer ref={this.layer}>
          <Text text="Try to drag a star" />
          ))}
        </Layer>
      </Stage>
    );
  }
}
```

**Comment by damiangreen** [comment]
Should this approach work for stage?
I tried it but get
```
const stageRef: React.RefObject<Konva.Stage> = createRef()
....
 <Stage
        ref={stageRef}
...
```

> Type 'Stage' is missing the following properties from type 'Stage': context, setState, forceUpdate, render, and 3 more.
>   Overload 2 of 2, '(props: StageProps & KonvaN
>

**Comment by lavrton** [comment]
@damiangreen looks like it is not working. I will make a fix soon.

**Comment by lavrton** [comment]
Should work ok with `react-konva@16.13.0-6`

**Comment by damiangreen** [comment]
hey thanks for the super  speedy response.
I just bumped the package

```
const stageRef = useRef<Konva.Stage>(null)
...
      <Stage
        ref={stageRef}
```
but get 

> >No overload matches this call.
  Overload 1 of 2, '(props: Readonly<StageProps & KonvaNodeEvents>): Stage', gave the following error.
    Type 'MutableRefObject<Stage>' is not assignable to type 'LegacyRef<Stage>'.
      Type 'MutableRefObject<Stage>' is not assignable to type 'RefObject<Stage>'.
        Types of property 'current' are incompatible.
          Type 'Stage' is missing the following properties from type 'Stage': context, setState, forceUpdate, render, and 3 more.
  Overload 2 of 2, '(props: StageProps & KonvaNodeEvents, context?: any): Stage', gave the following error.
    Type 'MutableRefObject<Stage>' is not assignable to type 'LegacyRef<Stage>'.
      Type 'MutableRefObject<Stage>' is not assignable to type 'RefObject<Stage>'.ts(2769)

is `Konva.Stage` the correct generic argument for `useRef`?
🙇

**Comment by lavrton** [comment]
Can you make a small demo repo? I just tried this:

```js
const App = () => {
  const ref = React.useRef<Konva.Stage>(null);
  return (
    <Stage width={window.innerWidth} height={window.innerHeight} ref={ref} />
  );
};
```

Works ok for me.

**Comment by AKclown** [comment]
`
    stageElement: RefObject<Konva.Stage> | undefined

<Stage
                    ref={this.stageElement}
...
`
Property 'getStage' does not exist on type 'RefObject<Stage>'.  

Why doesn't the attribute exist?

**Comment by MichaelVoelkel** [comment]
Hi,

closed but...

```
const rect: RefObject<Konva.Rect> = useRef(null);
// ...
<React.Fragment>
                            <Rect ref={rect} width={entity.width} height={entity.height} fill="red" />
                            <Transformer node={rect} /> 
                        </React.Fragment>
```
`entity` is my private stuff, not relevant. Well, but node complains about the `node` attribute for `Transformer`:
```
Type 'RefObject<Rect>' is missing the following properties from type 'Rect': _sceneFunc, cornerRadius, _centroid, colorKey, and 270 more.
```
