### ISSUE TITLE
Facing the issue now with Next.js 14:

### ISSUE THREAD

**Issue by danesto** [konvajs/react-konva#787]
### **Canvas not found issue now with Next.js 14:**

version: "next": "14.0.4".

App wan't build with error:
``` 
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error 
Error: Cannot find module 'canvas' 
```

Component that uses Konva is dynamically imported:
```
const Canvas = dynamic(() => import("@/components/canvas/canvas"), {
  ssr: false,
});
```

And the component is defined outside of the app directory.

NextConfig:
```
const nextConfig = {
  webpack: (config) => {
    config.externals = [...config.externals, { canvas: "canvas" }]; // required to make Konva & react-konva work
    return config;
  },
.....
```

Anyone maybe knows the workaround? I can't get it to deploy on Vercel cause of the error. Thanks in advance!

_Originally posted by @danesto in https://github.com/konvajs/react-konva/issues/588#issuecomment-1910421325_

**Comment by myassir** [comment]
Using `'use client';` on the lazy loaded component solved the issue for me.

**Comment by danesto** [comment]
Already tried, it didn't work for me for some reason. Finally managed to
build it locally by installing some packages that canvas package was
requiring apparently in order to run, now am trying to figure out how to
make it work on Vercel as well.

**Comment by lavrton** [comment]
Just tried with the last next 14, all works good for me with the approach described in the readme.

@kev-bee please make a little repository to reproduce.

**Comment by dev-fredericfox** [comment]
Not working on 14.1.3 (tested with static export).

**Comment by GVAmaresh** [comment]
I've tried adding the following configuration in `next.config.mjs` to resolve the canvas-related issue:
```
export default {
  webpack: (config) => {
    config.resolve.fallback = {
      ...config.resolve.fallback,
      canvas: false,
    };
    return config;
  },
};
```
and restart the server
---
Name: Konva compatibility issue with NextJS and TypeScript
Issue: Module not found: './canvas'
Solution: I am instructing Webpack to neglect the canvas module in the final bundle. 
---

## Expected Behavior
The Konva components should render correctly without any errors or issues.

## Actual Behavior
The application throws errors related to Konva nodes not being recognized and issues with rendering certain components. Specific error messages include:
- `Konva has no node with the type source. Group will be used instead.`
- `Text components are not supported for now in ReactKonva.`
- `Cannot read properties of undefined (reading 'getParent')`

The above errors encountered in the application regarding Konva, Text, getParent issues can be addressed through research and tailored solutions as I have successfully implemented solutions that work effectively for my application

## Environment
- NextJS version: [e.g., 13.0.0]
- TypeScript version: [e.g., 4.8.4]
- Konva version: [e.g., 8.3.14]
- react-konva version: [e.g., 18.2.0]

**Comment by infix** [comment]
Next 14.2 on cloudflare pages crashes when trying to bundle konva. downgrading to 14.1 fixes solves this issue for me, need to take a closer look at this

**Comment by RobotScribe** [comment]
Working with Next 15.2.2 and I have the same issue
Installing `canvas@next` fixed the issue but that means adding a useless dependency

**Comment by lavrton** [comment]
Looks like mismatch in react and react-konva versions.
