### ISSUE TITLE
I get err when using Hooks API in react@16.7.0-alpha.2

### ISSUE THREAD

**Issue by kawasako** [konvajs/react-konva#293]
I tried Hooks API with react-konva. I get err `TypeError: dispatcher.useState is not a function`.
This is still alpha version, so I just reported it.

```js
import React, { useState, useEffect, useRef } from 'react'
import { Filters } from 'konva'
import { Image } from 'react-konva'

const BlurImage = ({ src, blurRadius = 10 }) => {
  const [image, setImage] = useState(null)
  const node = useRef(null)
  useEffect(() => {
    const image = new window.Image()
    image.src = src
    image.onload = () => {
      setImage(image)
      if (node && node.current) {
        node.current.cache()
      }
    }
  })
  return (
    <Image ref={node} image={image} filters={Filters.Blur} blurRadius={blurRadius}></Image>
  )
}

export default BlurImage
```

```
  1462 | 
  1463 | function useState(initialState) {
  1464 |   var dispatcher = resolveDispatcher();
> 1465 |   return dispatcher.useState(initialState);
       | ^  
  1466 | }
  1467 | 
  1468 | function useReducer(reducer, initialState, initialAction) {
```

**Comment by lavrton** [comment]
Thanks a lot for the report. I am going to work with it closer to `16.7` release

**Comment by jquense** [comment]
Support for hooks should just be a bump in the react-reconciler and react packages. Any chance you'd want to release a beta/prerelease version using react@next? I'd be happy to test it out and help address any issues (i've some experience with react renderers having built a few)

**Comment by lavrton** [comment]
Just made a prelease `16.8.0-1` with the support of Hooks.

```
npm install react-konva@next
```
Please try it. Let me know if it works ok.  Will publish with `latest` tag later.
